import { RouteInfo } from "./sidebar.metadata";
export const ROUTES: RouteInfo[] = [
  {
    path: "",
    title: "MENUITEMS.MAIN.TEXT",
    iconType: "",
    icon: "",
    class: "",
    groupTitle: true,
    badge: "",
    badgeClass: "",
    role: ["All"],
    submenu: [],
  },

  // Admin Modules
  // {
  //   path: "",
  //   title: "MENUITEMS.DASHBOARD.TEXT",
  //   iconType: "feather",
  //   icon: "monitor",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [
  //     {
  //       path: "/admin/dashboard/main",
  //       title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD1",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/admin/dashboard/dashboard2",
  //       title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD2",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //   ],
  // },

  // Employee Modules
  {
    path: "/employee/dashboard",
    title: "MENUITEMS.EMPLOYEE.DASHBOARD",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Employee"],
    submenu: [],
  },

  // Client Modules
  {
    path: "/client/dashboard",
    title: "MENUITEMS.CLIENT.DASHBOARD",
    iconType: "feather",
    icon: "airplay",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Client"],
    submenu: [],
  },
  // {
  //   path: "",
  //   title: "Users",
  //   iconType: "feather",
  //   icon: "users",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [ {
  //     path: "/Users/user-list",
  //     title: "User List",
  //     iconType: "",
  //     icon: "",
  //     class: "ml-menu",
  //     groupTitle: false,
  //     badge: "",
  //     badgeClass: "",
  //     role: [""],
  //     submenu: [],
  //   },
  //   {
  //     path: "/Users/add-user",
  //     title: "Add User",
  //     iconType: "",
  //     icon: "",
  //     class: "ml-menu",
  //     groupTitle: false,
  //     badge: "",
  //     badgeClass: "",
  //     role: [""],
  //     submenu: [],
  //   },]
  // },
  // {
  //   path: "",
  //   title: "Company",
  //   iconType: "feather",
  //   icon: "feather",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [ {
  //     path: "/Company/allcompany",
  //     title: "All Company",
  //     iconType: "",
  //     icon: "",
  //     class: "ml-menu",
  //     groupTitle: false,
  //     badge: "",
  //     badgeClass: "",
  //     role: [""],
  //     submenu: [],
  //   },
  //   {
  //     path: "/Company/add-company",
  //     title: "Add Company",
  //     iconType: "",
  //     icon: "",
  //     class: "ml-menu",
  //     groupTitle: false,
  //     badge: "",
  //     badgeClass: "",
  //     role: [""],
  //     submenu: [],
  //   },]
  // },
  // Common Modules
  {
    path: "",
    title: "Authentication",
    iconType: "feather",
    icon: "user-check",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "/authentication/signin",
        title: "Sign In",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

      {
        path: "/authentication/forgot-password",
        title: "Forgot Password",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

      {
        path: "/authentication/page404",
        title: "404 - Not Found",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "/authentication/page500",
        title: "500 - Server Error",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
    ],
  },

  // {
  //   path: "",
  //   title: "Settings",
  //   iconType: "settings",
  //   icon: "settings",
  //   class: "menu-toggle",
  //   groupTitle: false,
  //   badge: "",
  //   badgeClass: "",
  //   role: ["Admin"],
  //   submenu: [
  //     {
  //       path: "/setting/general-settings",
  //       title: "General Setting",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/setting/shared",
  //       title: "Shared",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "/setting/payment-settings",
  //       title: "Payment Setting",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },
  //     {
  //       path: "setting/pricing-package",
  //       title: "Pricing Package",
  //       iconType: "",
  //       icon: "",
  //       class: "ml-menu",
  //       groupTitle: false,
  //       badge: "",
  //       badgeClass: "",
  //       role: [""],
  //       submenu: [],
  //     },


  //   ],
  // },


  {
    path: "",
    title: "Superadmin",
    iconType: "feather",
    icon: "feather",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "",
        title: "MENUITEMS.DASHBOARD.TEXT",
        iconType: "feather",
        icon: "monitor",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [
          {
            path: "/admin/dashboard/main",
            title: "MENUITEMS.DASHBOARD.LIST.DASHBOARD1",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            submenu: [],
          },

        ],
      },
      {
        path: "",
        title: "Users",
        iconType: "feather",
        icon: "users",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [ {
          path: "/Users/user-list",
          title: "User List",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          submenu: [],
        },
        ]
      },
      {
        path: "/Company/allcompany",
        title: "Company",
        iconType: "feather",
        icon: "feather",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [ {
          path: "/Company/allcompany",
          title: "All Company",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          submenu: [],
        },
       ]
      },

      {
        path: "",
        title: "Settings",
        iconType: "settings",
        icon: "settings",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: [
          {
            path: "/setting/general-settings",
            title: "General Setting",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            submenu: [],
          },
          {
            path: "/setting/shared",
            title: "Shared",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            submenu: [],
          },
          {
            path: "/setting/payment-settings",
            title: "Payment Setting",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            submenu: [],
          },
          {
            path: "setting/pricing-package",
            title: "Pricing Package",
            iconType: "",
            icon: "",
            class: "ml-menu",
            groupTitle: false,
            badge: "",
            badgeClass: "",
            role: [""],
            submenu: [],
          },


        ],
      },
    ]
  },

  {
    path: "",
    title: "Connector",
    iconType: "feather",
    icon: "home",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "Connector/security-status",
        title: "Security Status",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "Connector/alerting",
        title: "Alerting",
        iconType: "feather",
        icon: "monitor",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "Connector/high-availability",
        title: "High Avaliability",
        iconType: "feather",
        icon: "monitor",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "Connector/hardware-metrics",
        title: "Hardware Metrics Monitor",
        iconType: "feather",
        icon: "monitor",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "Connector/configuration",
        title: "Configuration",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        submenu: []
      },
      {
        path: "Connector/subaccount",
        title: "Subaccount",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: ["Admin"],
        // submenu:[]
       submenu: [
        {
          path: "Connector/subaccount/all-subaccount",

          title: "All Subaccount",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: ["Admin"],
          submenu: []
      },


        // {
        //   //path: "",
        //   path:"Connector/subaccount/cloud-to-on-premises",
        //   title: "Cloud To On-Premises",
        //   iconType: "",
        //   icon: "",
        //   class: "ml-menu",
        //   groupTitle: false,
        //   badge: "",
        //   badgeClass: "",
        //   role: ["Admin"],
        //   submenu: []
        // },
      //   {
      //     path: "Connector/subaccount/on-premise-to-cloud",
      //   // path:"Connector/subaccount/cloud-to-on-premises",
      //     title: "On-Premises To Cloud",
      //     iconType: "",
      //     icon: "",
      //     class: "ml-menu",
      //     groupTitle: false,
      //     badge: "",
      //     badgeClass: "",
      //     role: ["Admin"],
      //     submenu: []
      // },
    //   {
    //     path: "Connector/subaccount/monitor1",

    //     title: "Monitor(Cloud To On-Premises)",
    //     iconType: "",
    //     icon: "",
    //     class: "ml-menu",
    //     groupTitle: false,
    //     badge: "",
    //     badgeClass: "",
    //     role: ["Admin"],
    //     submenu: []
    // },
  //   {
  //     path: "Connector/subaccount/monitor2",

  //     title: "Monitor(On-Premises To Cloud)",
  //     iconType: "",
  //     icon: "",
  //     class: "ml-menu",
  //     groupTitle: false,
  //     badge: "",
  //     badgeClass: "",
  //     role: ["Admin"],
  //     submenu: []
  // },
//   {
//     path: "Connector/subaccount/audits",

//     title: "Audits",
//     iconType: "",
//     icon: "",
//     class: "ml-menu",
//     groupTitle: false,
//     badge: "",
//     badgeClass: "",
//     role: ["Admin"],
//     submenu: []
// },
// {
//   path: "Connector/subaccount/log-traces",

//   title: "Log and Trace Files",
//   iconType: "",
//   icon: "",
//   class: "ml-menu",
//   groupTitle: false,
//   badge: "",
//   badgeClass: "",
//   role: ["Admin"],
//   submenu: []
// },
    ]
      },



    ]
  },
  {
    path: "",
    title: "ERP",
    iconType: "feather",
    icon: "folder",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "ERP/Customer",
        title: "Customer",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [{
          path: "ERP/Customer/agreement",
          title: "Agreement",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          submenu: [],
        }],
      },
      {
        path: "ERP/Prospect",
        title: "Prospect",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [{
          path: "ERP/Prospect/proposal",
          title: "Proposal",
          iconType: "",
          icon: "",
          class: "ml-menu",
          groupTitle: false,
          badge: "",
          badgeClass: "",
          role: [""],
          submenu: [],
        }],
      },

    ]
  },

  {
    path: "",
    title: "Styles",
    iconType: "feather",
    icon: "list",
    class: "menu-toggle",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["Admin"],
    submenu: [
      {
        path: "Styles/theme",
        title: "Theme",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "Styles/font-size",
        title: "Font Size",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },
      {
        path: "Styles/style-switcher",
        title: "Style Switcher",
        iconType: "",
        icon: "",
        class: "ml-menu",
        groupTitle: false,
        badge: "",
        badgeClass: "",
        role: [""],
        submenu: [],
      },

    ]
  },



];
